### ISSUE TITLE
There is only one failed test in report

### ISSUE THREAD

**Issue by filipehb** [jz-jess/RobotEyes#23]
**Describe the bug**
After executing suit with 2 tests or more, the report of all tests isn't generated.

**To Reproduce**
1. Create two test cases.
[
![tests](https://user-images.githubusercontent.com/869359/53519636-7bf8bf80-3ab2-11e9-96ca-36a8199ac520.png)
](url)
2. Execute tests.
3. See report.

**Expected behavior**
All tests should be in report.

**Screenshots**
![report](https://user-images.githubusercontent.com/869359/53520003-58824480-3ab3-11e9-880f-39d815393513.png)
Report

**Desktop (please complete the following information):**
 - OS: Win 10 Pro
 - Browser Chrome
 - Version 72.0.3626.119

**Additional context**

**Comment by filipehb** [comment]
@jz-jess, I can analyze this problem and submit a pull request. What do you think?
[test.zip](https://github.com/jz-jess/RobotEyes/files/2912153/test.zip)

**Comment by jz-jess** [comment]
@filipehb You can try running `reportgen path/to/results folder` to fix this issue.
The report autogeneration could be buggy, because it tends to delete report whose last modified at is more than 5 seconds. Feel free to analyse it though.

**Comment by jz-jess** [comment]
@filipehb I think this could be happening because of the slowing down of selenium execution by using set selenium speed.

**Comment by jz-jess** [comment]
@filipehb I have raised a PR with a possible fix since previous time difference calculation was wrong.
Can you please run your tests using this branch?
https://github.com/jz-jess/RobotEyes/pull/24

**Comment by filipehb** [comment]
@jz-jess, i got this error sometimes, and visual report has the same behavior.


![image](https://user-images.githubusercontent.com/869359/53585596-1285b900-3b65-11e9-8b28-b1598687fb78.png)
[reports.zip](https://github.com/jz-jess/RobotEyes/files/2916136/reports.zip)

**Comment by jz-jess** [comment]
@filipehb Thank you! Let me take a look at this issue. Keep you posted.

**Comment by jz-jess** [comment]
@filipehb I was able to reproduce the issue. The issue is caused because of keyword `set selenium speed  1`.  The slow execution results in time difference threshold to more than 10 seconds between tests. Auto generation of report works in the following way.
- Since a new RobotEyes instance is created for each test, there is no way of knowing if the `visualReport.html` file belongs to the current test run.
- Code checks for the last modified time of `visualReport.html` and gets the difference between last modified and current time. If the difference is more than 5 seconds, it assumes that `visualReport.html` belongs to an older test run. It deletes the file and creates a new file. The current test result gets written to it.

In your case the difference crosses 10+ seconds between each test, which is why you only see the last test in the execution in the report. I would suggest you to run an alternative command to generate the report manually. `reportgen path/to/result folder` or  `reportgen` if there is no result folder.

You can also view an interactive report by running `eyes /path/to/results` or `eyes` if there is no result folder.

**Comment by filipehb** [comment]
@jz-jess, i remove the keyword `set selenium speed 1` and `timeout=5` parameter of `Wait Until Element Is Visible`, but the issue continues to me.

![testrobot](https://user-images.githubusercontent.com/869359/53637656-7f9b5c00-3c02-11e9-8c43-176f30212f38.png)

**Comment by jz-jess** [comment]
@filipehb I could not reproduce the issue after removing set selenium speed.
You don't have to remove timeout of wait until element is visible.

Did you try using the fix in the pull request?

**Comment by filipehb** [comment]
@jz-jess, i got this error if use PR:

![image](https://user-images.githubusercontent.com/869359/53638097-f127da00-3c03-11e9-95a7-a9ce2b29acc9.png)

**Comment by jz-jess** [comment]
@filipehb I have fixed that issue. Please pull the code and try once again.

**Comment by filipehb** [comment]
@jz-jess, sorry i didn't see the new commit. The TypeError problem is solved, but in the report i got the same issue.

[reports.zip](https://github.com/jz-jess/RobotEyes/files/2919407/reports.zip)

![image](https://user-images.githubusercontent.com/869359/53638764-19b0d380-3c06-11e9-8401-27f806a99eb3.png)

**Comment by jz-jess** [comment]
@filipehb okay.  After you run your tests, please run command `reportgen <results folder>` or `reportgen` if no results folder. This should generate a fresh report. Does this solve your issue?

**Comment by jz-jess** [comment]
@filipehb I have pushed another commit which doubles the threshold. Please give it one last shot and see if it fixes your problem. I dont see any issues in my system. I dont have a windows system
<img width="1279" alt="screenshot 2019-03-01 at 6 32 29 pm" src="https://user-images.githubusercontent.com/7547737/53639869-7b962b00-3c50-11e9-926f-120be3670c8d.png">

**Comment by filipehb** [comment]
> @filipehb okay. After you run your tests, please run command `reportgen <results folder>` or `reportgen` if no results folder. This should generate a fresh report. Does this solve your issue?

Yes, solved :D.  Thx!

> @filipehb I have pushed another commit which doubles the threshold. Please give it one last shot and see if it fixes your problem. I dont see any issues in my system. I dont have a windows system
> <img alt="screenshot 2019-03-01 at 6 32 29 pm" width="1279" src="https://user-images.githubusercontent.com/7547737/53639869-7b962b00-3c50-11e9-926f-120be3670c8d.png">

I will test with new PR.

**Comment by filipehb** [comment]
@jz-jess, nice PR! Issue resolved for me 🥇.

**Comment by jz-jess** [comment]
@filipehb Great. Deploy this soon in the next release

**Comment by jz-jess** [comment]
Fix released in version 0.64
