### ISSUE TITLE
Custom folder to store baseline images

### ISSUE THREAD

**Issue by AllanMedeiros** [jz-jess/RobotEyes#44]
**Is your feature request related to a problem? Please describe.**
Screenshots for each browser can be different, so we need to store them in different places.

**Describe the solution you'd like**
Just a way to set the directory where the images will be saved.
Then I'd add a Browser variable to the path.

**Describe alternatives you've considered**
I've implemented a screenshot comparison by myself, but lacks the blurring dynamic fields feature, which is a must in my case.

**Additional context**
N/A

**Comment by jz-jess** [comment]
@AllanMedeiros Baseline directory needs to be passed via the command line. Ex `-v images_dir:baseline/chrome`. Were you able to try this? Let me know if there is something additional that needs to be done to fix your usecase.

**Comment by AllanMedeiros** [comment]
My bad, just started implementing this library and missed that.
Thanks!
