### ISSUE TITLE
Could parse comparison output: compare: width or height exceeds limit 

### ISSUE THREAD

**Issue by Aarushigarg3** [jz-jess/RobotEyes#49]
Getting the following issue while executing the visual automation test cases: 

Could parse comparison output: compare: width or height exceeds limit  @ error/cache.c/OpenPixelCache/3671.

**Comment by jz-jess** [comment]
@Aarushigarg3 Could you please update the library to a later version and see if it still persists?

**Comment by Aarushigarg3** [comment]
@jz-jess i have the version `robotframework-eyes 1.3.0`, but still getting the same issue

**Comment by jz-jess** [comment]
@Aarushigarg3 Could you run command `compare -metric RMSE -subimage-search -dissimilarity-threshold 1.0 image1_path image2_path image3_path`  on your terminal and confirm the output please?

**Comment by Aarushigarg3** [comment]
@jz-jess gave the whole path, but still couldn't get through, getting same error!
<img width="1220" alt="Screenshot 2020-02-11 at 12 57 37 PM" src="https://user-images.githubusercontent.com/35030326/74217627-03444080-4cce-11ea-9e68-72c792b7bc8b.png">

**Comment by jz-jess** [comment]
You also need to pass a third argument, image path to generate the diff image

**Comment by Aarushigarg3** [comment]
@jz-jess I did that as well 

<img width="1227" alt="Screenshot 2020-02-11 at 1 15 54 PM" src="https://user-images.githubusercontent.com/35030326/74218624-89618680-4cd0-11ea-8e29-0483ff61faa5.png">

**Comment by jz-jess** [comment]
@Aarushigarg3 This is an issue with ImageMagick and not with the library. The size of the images being compared is exceeding the limit set in Imagemagick policy in your machine. You could try increasing the limit. Please check
http://www.imagemagick.org/discourse-server/viewtopic.php?t=34044

I will look at resizing the images to an acceptable limit before comparing for the next release. Could you tell me what the limit for height width is in your machine?

**Comment by jz-jess** [comment]
Closing this on account of inactivity. Feel free to re-open if necessary
