### ISSUE TITLE
Remove dependency S2L lib

### ISSUE THREAD

**Issue by friendlyfreedom** [jz-jess/RobotEyes#53]
**Is your feature request related to a problem? Please describe.**
I've not installed Selenium2Library, as I'm using SeleniumLibrary, which is also the default of RobotEyes, but when installing with pip, S2L is automatically installed as a depencancy, but it works fine without.

**Describe the solution you'd like**
remove robotframework-selenium2library from install_requires in Setup.py

**Comment by jz-jess** [comment]
Removing SeleniumLibrary and Selenium2Library dependency. Will add SeleniumLibrary dependency back to setup if or when Selenium2Library is deprecated

**Comment by jz-jess** [comment]
This will go out in release 1.3.1

**Comment by jz-jess** [comment]
Released in version 1.3.2
