### ISSUE TITLE
How to check visualReport on Jenkins remotely

### ISSUE THREAD

**Issue by Jun-Zhu-Trend** [jz-jess/RobotEyes#57]
**Describe the bug**
The image path is absolute path which is embedded when created, and when using Jenkins HTML report plugin, it cannot show the report well , how can I configure to show it on Jenkins server correctly ?

<img width="866" alt="1" src="https://user-images.githubusercontent.com/66586973/84613268-83d1b280-aef5-11ea-9c64-b3d0f8591fa1.png">
The path "href="C:\ci-l10n\workspace\I18N\Test\Jun_Win_Test\regression\base\VisualDiffGoogle\img1.png"" is that path on my jenkins node build machine.

Here is my configuration on Jenkins server:
<img width="624" alt="2" src="https://user-images.githubusercontent.com/66586973/84613503-ea56d080-aef5-11ea-9ea2-832a6a4dd23b.png">

I run command like below:
(cd <root folder where *.robot exists, ex:\>C:\ci-l10n\workspace\I18N\Test\Jun_Win_Test\regression)
robot -d results -v images_dir:base .

Any ideas ?
thanks a lot for your help.

**Comment by Jun-Zhu-Trend** [comment]
I use one alternative way to use another python script to update the report HTML by using relative path in the report HTML, and it works, like below:
"href=".\base\VisualDiffGoogle\img1.png"
Since it needs me to write another script to update the script manually,  I am not sure whether there is a better way to generate the visualreport directly by using relative path inside it.

**Comment by jz-jess** [comment]
@Jun-Zhu-Trend Thanks for using the library.
I went through the code and it does look like absolute path is used for baseline folder. Could you please confirm if the actual and the diff images also contain absolute path in your local system?

**Comment by jz-jess** [comment]
@Jun-Zhu-Trend For the time being, instead of using your own script you can generate the report again with relative paths by using the following command instead,
`reportgen --baseline=<baseline image folder> --results=<results folder>` . Just pass relative paths to baseline directoy and results/output directory. This should solve the problem with absolute path

**Comment by Jun-Zhu-Trend** [comment]
I just tried to genereate the report again after run with : reportgen --baseline=base --results=results .
it works, 
thanks a lot.
