### ISSUE TITLE
join() argument must be str or bytes, not 'NoneType' when run  Open Eyes|lib='Selenium2Library'|tolerance=5 

### ISSUE THREAD

**Issue by nixuewei** [jz-jess/RobotEyes#59]
**Describe the bug**
join() argument must be str or bytes, not 'NoneType' when run  Open Eyes|lib='Selenium2Library'|tolerance=5 

**To Reproduce**
1. install pip install robotframework-eyes
2. install Imagemagick7 on windows10 or macos Catalina 10.15.5
3. copy code
`*** Settings ***
Test Teardown
Library           SeleniumLibrary
Library           RobotEyes

*** Test Cases ***
Sample visual regression test case
    # Name of the example test case
    Open Browser    https://www.baidu.com/    chrome
    Maximize Browser Window
    Open Eyes    lib='Selenium2Library'    tolerance=5
    Wait Until Element Is Visible    id=kw
    Capture Full Screen
    Compare Images
    Close Browser`

**Expected behavior**
run successfully

**Screenshots**
Starting test: CBTCTest.Visual Regression.Sample visual regression test case
20200728 12:04:23.045 :  INFO : Opening browser 'chrome' to base url 'https://www.baidu.com/'.
20200728 12:04:33.229 :  FAIL : TypeError: join() argument must be str or bytes, not 'NoneType'
Ending test: CBTCTest.Visual Regression.Sample visual regression test case

**Desktop (please complete the following information):**
 - OS: windows10 or macos Catalina 10.15.5
 - Browser [chrome]

**Comment by jz-jess** [comment]
@nixuewei Did you pass the path to baseline directory and output directory when running tests. Refer the ReadMe for the command.

**Comment by nixuewei** [comment]
sorry for my misunderstanding the document, after running on command, it works well. so great. thank you! please close it

**Comment by jz-jess** [comment]
@nixuewei That's alright. I will add a validation for the path in the upcoming release to avoid any confusion. Keeping this ticket open until then.

**Comment by nixuewei** [comment]
that was great!
