### ISSUE TITLE
Update to use of SeleniumLibrary

### ISSUE THREAD

**Issue by s-galante** [jz-jess/RobotEyes#6]
Any chance there will be an update to the base to include the shift from Selenium2Library to SeleniumLibrary as Selenium2Library will be considered deprecated in the latest version per:
http://robotframework.org/Selenium2Library/Selenium2Library.html

I currently use a modded init file to target the SeleniumLibrary to limit the need to install the older library on my docker calls for basic image testing.  Currently it looks like it may only effect the a few calls and as of now the direct change to the call in open_eyes works as is without mods to the other code.

**Comment by jz-jess** [comment]
@s-galante I got some time to work on this today. Here is the pull request.

**Comment by jz-jess** [comment]
Pull request has been merged. Support for SeleniumLibrary in version 0.56. pip install robotframework-eyes==0.56. Closing this. Thanks @s-galante

**Comment by DiegoSanchezE** [comment]
Hi Jess, did this improvement get carried into v0.58 or am I missing something?
Thanks!

**Comment by DiegoSanchezE** [comment]
Sweet! Thanks!
