### ISSUE TITLE
Support semicolumn for locator elements

### ISSUE THREAD

**Issue by leeuwe** [jz-jess/RobotEyes#77]
Currently it seems only `=` is supported. Seleniumlibrary has also adapted the semicolumn, for the following reason:

> The explicit locator strategy is specified with a prefix using either syntax strategy:value or strategy=value. The former syntax is preferred because the latter is identical to Robot Framework's named argument syntax and that can cause problems.

**Describe the solution you'd like**
Please add support for semicolumn as well. This will help preventing syntax errors for users (like me) who are accustomed to using the semicolumn

**Comment by jz-jess** [comment]
@leeuwe Thanks for raising the issue. I haven't been actively tracking changes in SeleniumLibrary. Will add this support as part of the next release.

**Comment by jz-jess** [comment]
Added this support in release 1.5.3.

**Comment by jz-jess** [comment]
Closing this. Please re open if it doesnt work

**Comment by leeuwe** [comment]
Verified. Working with both Blur function and selectors. Tested on ID and CSS selectors.
