### ISSUE TITLE
The visualReport should display images withour a blur

### ISSUE THREAD

**Issue by MininAS** [jz-jess/RobotEyes#92]
Does it possible to do that visualReport displays images without a blur?
A very small image looks horrible.

Example with the microphom from the google search input field:
![image](https://user-images.githubusercontent.com/48047242/115949683-65f2b800-a4df-11eb-8d3e-b1ceb90999e3.png)

**Comment by jz-jess** [comment]
This is because small icons are saved with larger dimensions, it ends up looking stretched. I can enhance the capture element keyword to additionally take dimensions to save the image in. I will have to check if there's a way to automatically do this

**Comment by MininAS** [comment]
Hmm... The visual_images folders contain saved images with own dimensions, i don't see some icons are saved with larger dimensions.
![image](https://user-images.githubusercontent.com/48047242/115951319-cf2af900-a4e8-11eb-99b4-8d806018e666.png)

**Comment by jz-jess** [comment]
My bad. I had fixed the dimensions issue a while back. This issue is because the report html contains fixed width and height for each image in the table. Retaining the original image width and height might probably make the table look uneven. Will check it out. Meanwhile, if you are able to fix the css of the table cell, then you can raise a PR or send me the css changes.

**Comment by MininAS** [comment]
fixed width and height for each image in the table - is good!!!

**Comment by MininAS** [comment]
I assume that is the browser does blur for small image when it is displayed in bigger size then it is

**Comment by jz-jess** [comment]
Yes because the width and height is fixed. Smaller images get stretched width and height wise

**Comment by MininAS** [comment]
Found some solution http://jsfiddle.net/namuol/VAXrL/1459/

**Comment by MininAS** [comment]
It seems it works
![image](https://user-images.githubusercontent.com/48047242/115953791-31d6c180-a4f6-11eb-86a6-6f6d5abbd6e1.png)

**Comment by jz-jess** [comment]
Can you raise a PR with the changes? You need to make the changes here https://github.com/jz-jess/RobotEyes/blob/master/RobotEyes/report_generator.py#L315 . From line 315 - 335. I can  test and merge it later. You can change the version 1.5.9 in setup.py

**Comment by MininAS** [comment]
Do you mean to add style for each <img>?

**Comment by jz-jess** [comment]
Ah I see. We can't just add it for everything right. This needs to be added only if the image is small?

**Comment by MininAS** [comment]
Very good question!!! I will check and let known

**Comment by MininAS** [comment]
I think we can image-rendering: pixelated; for any image.
![image](https://user-images.githubusercontent.com/48047242/115957655-68b7d200-a50c-11eb-9d14-55ca632b1977.png)

But my previous questiom is means to add style directly to HTML tag? Or we can add it to some common parent tag?

**Comment by jz-jess** [comment]
The style needs to be added to the img tags I believe. Not sure if adding to parent will work. You can add a css at the beginning within style tags img { width: 200 image-rendering: pixelated} something like this.

**Comment by MininAS** [comment]
```
$ git push origin Issue-92
remote: Permission to jz-jess/RobotEyes.git denied to MininAS.
fatal: unable to access 'https://github.com/jz-jess/RobotEyes.git/': The requested URL returned error: 403
```

**Comment by jz-jess** [comment]
https://opensource.com/article/19/7/create-pull-request-github

**Comment by MininAS** [comment]
https://github.com/jz-jess/RobotEyes/pull/94

**Comment by MininAS** [comment]
Should I do somethink else that PR can be pushed?

**Comment by jz-jess** [comment]
Nope. I need to test it as soon as I find sometime. Will merge after. You can install your branch into your systems meanwhile to use the fix.
