### ISSUE TITLE
No keyword with name 'Capture Element id=s-hotsearch-wrapper' found

### ISSUE THREAD

**Issue by zhangschunfeng** [jz-jess/RobotEyes#96]
**Describe the bug**

**No keyword with name 'Capture Element id=s-hotsearch-wrapper' found.**

**To Reproduce**

Open Browser    https://www.baidu.com/    firefox
Maximize Browser Window
Open Eyes    SeleniumLibrary  5
Wait Until Element Is Visible    id=s-hotsearch-wrapper
sleep  3
Capture Element id=s-hotsearch-wrapper
Close Browser
Compare Images
   
e.

**Comment by jz-jess** [comment]
@zhangschunfeng You should provide 2 spaces or more after capture element
